# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Recall.create(Category: "Consumer Products",Title: "Meijer Recalls Touch Point Baseboard Convection Heaters Due to a Fire Hazards",Summary: "Consumers should stop using this product unless otherwise instructed. It is illegal to resell or attempt to resell a recalled consumer product.",Details: "This recall involves Touch Point brand portable, electric baseboard convection heaters with model BBC-1500 and date code 0611. Touch Point can be found on the front of the product and the model and date code can be found on a silver sticker on the back side of the product. The heaters were manufactured in June 2011. The heaters are black and measures approximately 30-inches long by 6-inches deep by 12-inches high.")
Recall.create(Category: "Consumer Products",Title: "Toro Recalls Zero Turn Riding Mowers Due to Fire Hazard",Summary: "Consumers should stop using this product unless otherwise instructed. It is illegal to resell or attempt to resell a recalled consumer product. ",Details: "This recall involves 2012 and 2013 Toro Z Master Commercial 2000 Series ZRT riding mowers. The mowers are red and black. Toro and 2000 Series are printed on the side and Z Master Commercial on the front of the mowers. When viewed from the operators seat, the model and serial numbers are on a metal plate located at the front of the mower, below the seat, on the right-hand side. The following models and corresponding serial numbers are included in this recall: model number 74141 with serial numbers ranging from 312000101 to 312000784 and 313000101 to 313000364; model number 74143 with serial numbers ranging from 312000101 to 312000881 and 313000101 to 313000432; and model number 74145 with serial numbers ranging from 312000101 to 312001178 and 313000101 to 313000443.")
Recall.create(Category: "Foods, Medicines, Cosmetics",Title: "Advance Pharmaceutical Inc. Issues Voluntary Recall of One Lot of Enteric Coated Aspirin Tablets, 81 mg, Due to Health Risk",Summary: "",Details: "Advance Pharmaceutical Inc. today announced that this firm is conducting a voluntary nationwide recall to the user level of the over-the-counter drug product, Rugby label Enteric Coated Aspirin Tablets, 81 mg, Lot 13A026. Advance Pharmaceutical Inc. first initiated the recall on June 17, 2013, after receiving a complaint about a bottle labeled as Enteric Coated Aspirin Tablets, 81 mg, actually containing Acetaminophen 500 mg tablets.")